Repository CacaoTalk/ft_irc, pull requests merged in 2023-02, with the labels that each got.

#15 [REFACTOR] 변경사항 정리
  Channel.cpp
  Channel.hpp
  Command.cpp
  Command.hpp
  Makefile
  Message.cpp
  Message.hpp
  Reply.hpp
  Server.cpp
  Server.hpp
  User.cpp
  User.hpp
  main.cpp
Labels: REFACTOR

#19 [FIX] Command: PRIVMSG always put : front of text
  Command.cpp
Labels: FIX

#20 [BUG] Reply on client leave situation
  Command.cpp
  Message.cpp
  Server.cpp
  User.cpp
  User.hpp
Labels: bug

#23 [FIX] Modify conditional statement for checking empty nickname
  Command.cpp
Labels: bug

#24 [BUG] Server: select user or channel with find method
  Server.cpp
Labels: bug

#25 [FIX] Reply to all other users when a user change one's nickname
  Command.cpp
  User.hpp
Labels: bug, FIX

#26 [BUG] 없는 유저 KICK 했을 때 segmentation fault 발생 현상 수정
  Channel.cpp
  Channel.hpp
  Command.cpp
Labels: bug

#29 [FEAT] Bot : Service that recommend menu for meal
  Bot.cpp
  Bot.hpp
  Channel.cpp
  Channel.hpp
  Command.cpp
  Makefile
Labels: FEAT

#31 [BUG] NICK: reply message depending on joining channel #30
  Command.cpp
Labels: bug, FIX

#38 [FIX] Nickname - set max size, check is valid format
  Command.cpp
  CommonValue.hpp
  FormatValidator.cpp
  FormatValidator.hpp
  Makefile
  Reply.hpp
Labels: FIX

#40 [FIX] Channelname: max len(31, include '#'), check illegal char
  Command.cpp
  CommonValue.hpp
  FormatValidator.cpp
  FormatValidator.hpp
  Reply.hpp
Labels: FIX

#41 [FIX] add host to client source of reply message
  Channel.cpp
  Command.cpp
  Server.cpp
  User.cpp
  User.hpp
Labels: FIX

#46 REFACTOR/FIX: Command class with map, reply to unknown command
  Command.cpp
  Command.hpp
  Reply.hpp
  Server.cpp
  Server.hpp
Labels: REFACTOR, FIX

#47 [FIX] QUIT - remove check paramSize, reply Error to quiting client
  Command.cpp
  Server.cpp
  User.cpp
  User.hpp
Labels: FIX

#48 [BUG] Server: print message to console before delete channel
  Server.cpp
Labels: bug

#49 [FIX] Prefix check sent by client
  Command.cpp
  Message.cpp
  Message.hpp
Labels: FIX

#52 [FIX] set nonblocking fd on client socket, check errno set by read/write on client fd
  Server.cpp
  Server.hpp
Labels: FIX

#53 [BUG] remove kicked channel in my channel list
  Command.cpp
Labels: bug

#56 [BUG] clear user's myChannelList after leave all channels
  Command.cpp
  Server.cpp
  User.cpp
Labels: bug

#57 [FEAT] Server: set limit number of user/channel
  Command.cpp
  CommonValue.hpp
  Reply.hpp
  Server.cpp
  Server.hpp
Labels: FEAT

#59 [BUG] Command: check auth before run command
  Command.cpp
  Command.hpp
Labels: bug

#61 [REFACTOR] comment to functions using javadoc form
  Bot.cpp
  Channel.cpp
  Command.cpp
  FormatValidator.cpp
  Message.cpp
  Server.cpp
  User.cpp
Labels: REFACTOR

#62 [FIX] Server: Fail to accept only cut the connection of that client
  Server.cpp
Labels: FIX

#63 [REFACTOR] Move defined value to CommonValue.hpp
  Channel.cpp
  Channel.hpp
  Command.cpp
  CommonValue.hpp
  Message.cpp
  Message.hpp
  Server.cpp
  Server.hpp
  User.hpp
Labels: REFACTOR
