Repository CacaoTalk/ft_irc, pull requests merged in 2023-01, with the labels that each got.

#1 [FEAT] Handle commands
  .gitignore
  Channel.cpp
  Channel.hpp
  Makefile
  Message.cpp
  Message.hpp
  Server.cpp
  Server.hpp
  User.cpp
  User.hpp
  main.cpp
Labels: FEAT, REFACTOR

#3 [FEAT] Reply message
  Channel.cpp
  Channel.hpp
  Message.cpp
  Message.hpp
  Server.cpp
  Server.hpp
Labels: FEAT

#5 [BUG] Server: stop read client buffer after disconnectClient #4
  Server.cpp
  Server.hpp
Labels: bug

#11 [FIX] User: getNickname - empty nickname #8
  User.cpp
Labels: bug

#13 [FIX] Server: cmdNick - reply message contains origin nickname
  Server.cpp
Labels: bug
